# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hero < Formula
  desc "Spec-driven AI engineering workflow"
  homepage "https://github.com/bdwheeler/hero"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bdwheeler/hero/releases/download/v0.6.0/hero_0.6.0_darwin_amd64.tar.gz"
      sha256 "dc0f84ca51983b3bfe14f519e9abb6d72e292fc8dcc272ded2b8ce02f8fa61ca"

      define_method(:install) do
        bin.install "hero"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bdwheeler/hero/releases/download/v0.6.0/hero_0.6.0_darwin_arm64.tar.gz"
      sha256 "3c3ad4903f822f358c07a32c78050b31dd6c274a25129d9c9a97fac9d0dcebba"

      define_method(:install) do
        bin.install "hero"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bdwheeler/hero/releases/download/v0.6.0/hero_0.6.0_linux_amd64.tar.gz"
      sha256 "8fe017c3b3c2d76ea8bfda0887947dbad7aaaf2b4899fb691b2b822f56678ea0"
      define_method(:install) do
        bin.install "hero"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bdwheeler/hero/releases/download/v0.6.0/hero_0.6.0_linux_arm64.tar.gz"
      sha256 "81ea6b2d3dd5c56599875d9b671f63ee02d596eb1e6c6c4529c587c618b24a86"
      define_method(:install) do
        bin.install "hero"
      end
    end
  end

  test do
    system "#{bin}/hero", "--version"
  end
end
