# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hero < Formula
  desc "Spec-driven AI engineering workflow"
  homepage "https://github.com/bdwheeler/hero"
  version "0.5.14"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bdwheeler/hero/releases/download/v0.5.14/hero_0.5.14_darwin_amd64.tar.gz"
      sha256 "12bfacb9a59ffabd1aa76f2a6e47269d146da5888e25572648df2e235c7e53c5"

      define_method(:install) do
        bin.install "hero"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bdwheeler/hero/releases/download/v0.5.14/hero_0.5.14_darwin_arm64.tar.gz"
      sha256 "6608e4d35106e26a3b3e620a440d22e41af4a98904b0fc35c4264ec339b89347"

      define_method(:install) do
        bin.install "hero"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bdwheeler/hero/releases/download/v0.5.14/hero_0.5.14_linux_amd64.tar.gz"
      sha256 "cdaca9f228d2b299c10fbaa43e46592bf1c8bde72a68438864aef177eb7761d8"
      define_method(:install) do
        bin.install "hero"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bdwheeler/hero/releases/download/v0.5.14/hero_0.5.14_linux_arm64.tar.gz"
      sha256 "94225b7abf7d008854d8d474cfa8ea2663b6a7b11236dd7f3f10c7d16a8dbfd4"
      define_method(:install) do
        bin.install "hero"
      end
    end
  end

  test do
    system "#{bin}/hero", "--version"
  end
end
